import { useState, useEffect } from "react";

import api from "../services/api";
import ErrorAlert from "../components/ErrorAlert";
import LoadingSpinner from "../components/LoadingSpinner";

import styles from "./Forecast.module.css";

const MODEL_VERSION = "champion_v014_seed_ensemble";

export default function Forecast() {
  const [cities, setCities] = useState([]);
  const [citiesError, setCitiesError] = useState(null);
  const [selectedCity, setSelectedCity] = useState("");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showColdStart, setShowColdStart] = useState(false);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);

  // Load the city list once on mount.
  useEffect(() => {
    let active = true;
    api
      .get("/cities")
      .then((res) => {
        if (active) setCities(res.data.cities || []);
      })
      .catch(() => {
        if (active) setCitiesError("Could not load the city list. Is the API running?");
      });
    return () => {
      active = false;
    };
  }, []);

  const handleGenerate = async () => {
    if (!selectedCity) return;
    setLoading(true);
    setError(null);
    setData(null);
    setShowColdStart(false);

    // After 8s, hint that a sleeping Render free-tier server may be warming up.
    const coldStartTimer = setTimeout(() => setShowColdStart(true), 8000);

    try {
      const res = await api.get(`/forecast/${encodeURIComponent(selectedCity)}/briefing`);
      setData(res.data);
      setLastUpdated(new Date());
    } catch (err) {
      setError(
        err.response?.data?.detail ||
          "Failed to fetch the forecast. Please try again."
      );
    } finally {
      clearTimeout(coldStartTimer);
      setShowColdStart(false);
      setLoading(false);
    }
  };

  const formattedTime = lastUpdated
    ? new Intl.DateTimeFormat("en-US", { hour: "2-digit", minute: "2-digit" }).format(lastUpdated)
    : null;

  return (
    <div className={styles.page}>
      {/* Header */}
      <header className={styles.header}>
        <div>
          <h1 className={styles.title}>10-Day Flood Risk Forecast</h1>
          <p className={styles.subtitle}>
            Operational early-warning forecasts powered by ML + weather data
          </p>
        </div>
        <div className={styles.dataSource}>
          Data: Open-Meteo · Model: {MODEL_VERSION}
        </div>
      </header>

      {/* City selection bar */}
      <div className={styles.selectionBar}>
        <select
          className={styles.select}
          value={selectedCity}
          onChange={(e) => setSelectedCity(e.target.value)}
          aria-label="Select a city"
        >
          <option value="" disabled>
            Select a city…
          </option>
          {cities.map((c) => (
            <option key={c.name} value={c.name}>
              {c.name} — {c.district}
            </option>
          ))}
        </select>

        <button
          type="button"
          className={styles.generateBtn}
          onClick={handleGenerate}
          disabled={!selectedCity || loading}
        >
          {loading ? "Generating…" : "Generate Forecast"}
        </button>

        {formattedTime && (
          <span className={styles.lastUpdated}>Last updated: {formattedTime}</span>
        )}
      </div>

      {citiesError && <ErrorAlert message={citiesError} />}

      {/* Result area */}
      <div className={styles.result}>
        {error && <ErrorAlert message={error} onRetry={handleGenerate} />}

        {!error && loading && (
          <div className={styles.loading}>
            <LoadingSpinner size={28} variant="dark" />
            <p className={styles.loadingText}>
              Fetching weather forecast and computing risk scores for {selectedCity}…
            </p>
            {showColdStart && (
              <p className={styles.coldStart}>
                First request may take 15–20 seconds as the server warms up.
              </p>
            )}
          </div>
        )}

        {!error && !loading && !data && (
          <div className={styles.empty}>
            <p className={styles.emptyTitle}>
              Select a city above to view its 10-day flood risk forecast
            </p>
            <div className={styles.about}>
              <h2 className={styles.aboutTitle}>About this forecast</h2>
              <p className={styles.aboutBody}>
                Daily rainfall comes from the Open-Meteo weather service. Flood risk
                scores are produced by our CatBoost model ensemble (champion v014),
                and the plain-language briefing with per-day actions is generated by Gemini.
              </p>
            </div>
          </div>
        )}

        {/* Display sections are added in Phase C. */}
        {!error && !loading && data && (
          <div className={styles.placeholder}>
            Forecast loaded for {data.city}, {data.district}. Display sections coming next.
          </div>
        )}
      </div>
    </div>
  );
}
