import { useState, useEffect } from "react";

import { BookOpen, TrendingUp, ClipboardCheck, Lightbulb, AlertTriangle } from "lucide-react";

import api from "../services/api";
import ErrorAlert from "../components/ErrorAlert";
import LoadingSpinner from "../components/LoadingSpinner";
import SummaryStats from "../components/SummaryStats";
import ForecastChart from "../components/ForecastChart";
import DayCard from "../components/DayCard";

import styles from "./Forecast.module.css";

const MODEL_VERSION = "champion_v014_seed_ensemble";

export default function Forecast() {
  const [cities, setCities] = useState([]);
  const [citiesError, setCitiesError] = useState(null);
  const [selectedCity, setSelectedCity] = useState("");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showColdStart, setShowColdStart] = useState(false);
  const [error, setError] = useState(null);
  const [lastUpdated, setLastUpdated] = useState(null);

  // Load the city list once on mount.
  useEffect(() => {
    let active = true;
    api
      .get("/cities")
      .then((res) => {
        if (active) setCities(res.data.cities || []);
      })
      .catch(() => {
        if (active) setCitiesError("Could not load the city list. Is the API running?");
      });
    return () => {
      active = false;
    };
  }, []);

  const handleGenerate = async () => {
    if (!selectedCity) return;
    setLoading(true);
    setError(null);
    setData(null);
    setShowColdStart(false);

    // After 8s, hint that a sleeping Render free-tier server may be warming up.
    const coldStartTimer = setTimeout(() => setShowColdStart(true), 8000);

    try {
      const res = await api.get(`/forecast/${encodeURIComponent(selectedCity)}/briefing`);
      setData(res.data);
      setLastUpdated(new Date());
    } catch (err) {
      setError(
        err.response?.data?.detail ||
          "Failed to fetch the forecast. Please try again."
      );
    } finally {
      clearTimeout(coldStartTimer);
      setShowColdStart(false);
      setLoading(false);
    }
  };

  const formattedTime = lastUpdated
    ? new Intl.DateTimeFormat("en-US", { hour: "2-digit", minute: "2-digit" }).format(lastUpdated)
    : null;

  return (
    <div className={styles.page}>
      {/* Header */}
      <header className={styles.header}>
        <div>
          <h1 className={styles.title}>10-Day Flood Risk Forecast</h1>
          <p className={styles.subtitle}>
            Operational early-warning forecasts powered by ML + weather data
          </p>
        </div>
        <div className={styles.dataSource}>
          Data: Open-Meteo · Model: {MODEL_VERSION}
        </div>
      </header>

      {/* City selection bar */}
      <div className={styles.selectionBar}>
        <select
          className={styles.select}
          value={selectedCity}
          onChange={(e) => setSelectedCity(e.target.value)}
          aria-label="Select a city"
        >
          <option value="" disabled>
            Select a city…
          </option>
          {cities.map((c) => (
            <option key={c.name} value={c.name}>
              {c.name} — {c.district}
            </option>
          ))}
        </select>

        <button
          type="button"
          className={styles.generateBtn}
          onClick={handleGenerate}
          disabled={!selectedCity || loading}
        >
          {loading ? "Generating…" : "Generate Forecast"}
        </button>

        {formattedTime && (
          <span className={styles.lastUpdated}>Last updated: {formattedTime}</span>
        )}
      </div>

      {citiesError && <ErrorAlert message={citiesError} />}

      {/* Result area */}
      <div className={styles.result}>
        {error && <ErrorAlert message={error} onRetry={handleGenerate} />}

        {!error && loading && (
          <div className={styles.loading}>
            <LoadingSpinner size={28} variant="dark" />
            <p className={styles.loadingText}>
              Fetching weather forecast and computing risk scores for {selectedCity}…
            </p>
            {showColdStart && (
              <p className={styles.coldStart}>
                First request may take 15–20 seconds as the server warms up.
              </p>
            )}
          </div>
        )}

        {!error && !loading && !data && (
          <div className={styles.empty}>
            <p className={styles.emptyTitle}>
              Select a city above to view its 10-day flood risk forecast
            </p>
            <div className={styles.about}>
              <h2 className={styles.aboutTitle}>About this forecast</h2>
              <p className={styles.aboutBody}>
                Daily rainfall comes from the Open-Meteo weather service. Flood risk
                scores are produced by our CatBoost model ensemble (champion v014),
                and the plain-language briefing with per-day actions is generated by Gemini.
              </p>
              <p className={styles.aboutNote}>
                Forecasts use district-level environmental averages. For block-level
                precision, integrate high-resolution geospatial data — on the future
                improvements roadmap.
              </p>
            </div>
          </div>
        )}

        {!error && !loading && data && (() => {
          // Match each day's briefing action by date; missing → null (renders "—").
          const actionByDate = {};
          (data.briefing?.per_day_actions || []).forEach((a) => {
            actionByDate[a.date] = a.action;
          });

          return (
            <>
              {/* Section 1 — Executive Summary (only when briefing available) */}
              {data.briefing && (
                <section className={styles.card}>
                  <h2 className={styles.cardHeader}>
                    <BookOpen size={18} strokeWidth={2.2} />
                    Executive Summary
                  </h2>
                  <p className={styles.execSummary}>{data.briefing.executive_summary}</p>
                </section>
              )}

              {/* Summary stat chips — always render (independent of briefing) */}
              <section className={styles.card}>
                <SummaryStats summary={data.summary} forecast={data.forecast} />
              </section>

              {/* Section 2 — 10-Day Risk Timeline */}
              <section className={styles.card}>
                <h2 className={styles.cardHeader}>
                  <TrendingUp size={18} strokeWidth={2.2} />
                  10-Day Risk Timeline
                </h2>
                <ForecastChart forecast={data.forecast} />
              </section>

              {/* Section 3 — Day-by-Day Action Plan */}
              <section className={styles.section}>
                <h2 className={styles.sectionHeader}>
                  <ClipboardCheck size={18} strokeWidth={2.2} />
                  Day-by-Day Action Plan
                </h2>
                {!data.briefing && (
                  <div className={styles.briefingWarning}>
                    <AlertTriangle size={16} strokeWidth={2.2} />
                    AI briefing temporarily unavailable
                  </div>
                )}
                <div className={styles.dayGrid}>
                  {data.forecast.map((day) => (
                    <DayCard
                      key={day.date}
                      day={day}
                      action={actionByDate[day.date] ?? null}
                    />
                  ))}
                </div>
              </section>

              {/* Section 4 — Strategic Recommendation (only when briefing available) */}
              {data.briefing && (
                <section className={styles.recommendation}>
                  <h2 className={styles.recHeader}>
                    <Lightbulb size={18} strokeWidth={2.2} />
                    Strategic Recommendation
                  </h2>
                  <p className={styles.recBody}>{data.briefing.overall_recommendation}</p>
                </section>
              )}
            </>
          );
        })()}
      </div>
    </div>
  );
}
